#!/bin/bash
## Copyright (C) 2020 David Miguel Susano Pinto <carandraug@octave.org>
##
## Copying and distribution of this file, with or without modification,
## are permitted in any medium without royalty provided the copyright
## notice and this notice are preserved.  This file is offered as-is,
## without any warranty.

## Octave-Forge: image package bootstrap script
## Run this to generate the configure script

set -e        # halt if unhandled error

cd src/
aclocal -Im4  # get macros into aclocal.m4
autoconf      # generate configure script
