#! /bin/sh

if test $# -eq 1; then
  dir="$1"
else
  echo "usage: mkpkgadd directory" 1>&2
  exit 1
fi

cd $dir

m_files=`echo *.m`
cxx_files=`echo *.cc`
ln_files=`echo *.octlink`

if test "$m_files" != "*.m"; then
  sed -n 's/^[#%][#%]* *PKG_ADD: *//p' $m_files
fi

if test "$cxx_files" != "*.cc"; then
  sed -n -e 's,^//* *PKG_ADD: *,,p' \
         -e 's,^/\** *PKG_ADD: *\(.*\) \*/$,\1,p' $cxx_files
fi

if test "$ln_files" != "*.octlink" ; then
  cat $ln_files
fi
